In [1]:
import numpy as np
import import_ipynb
import Pipeline
import Data_Preparation
import DownloadingData

importing Jupyter notebook from Pipeline.ipynb
importing Jupyter notebook from DownloadingData.ipynb
importing Jupyter notebook from Testsetsplit.ipynb
StratifiedShuffleSplit(n_splits=1, random_state=42, test_size=0.2,
            train_size=None)
importing Jupyter notebook from MyTransformer.ipynb
importing Jupyter notebook from Data_Preparation.ipynb
[-118.51     34.26     29.     2119.5     433.     1164.      408.
    3.5409]
longitude             -118.5100
latitude                34.2600
housing_median_age      29.0000
total_rooms           2119.5000
total_bedrooms         433.0000
population            1164.0000
households             408.0000
median_income            3.5409
dtype: float64
[[-121.89     37.29     38.     ...  710.      339.        2.7042]
 [-121.93     37.05     14.     ...  306.      113.        6.4214]
 [-117.2      32.77     31.     ...  936.      462.        2.8621]
 ...
 [-116.4      34.09      9.     ... 2098.      765.        3.2723]
 [-118.01     33.82   

In [2]:
housing_train=Pipeline.housing_train_og
housing_labels=Data_Preparation.housing_labels


In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
lin_reg=LinearRegression()
lin_reg.fit(housing_train,housing_labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
some_data=Data_Preparation.housetraincopy.iloc[:5]
some_labels=housing_labels[:5]
some_data_prepared=Pipeline.full_pipeline.transform(some_data)

In [6]:
print("Predictions:",lin_reg.predict(some_data_prepared))

Predictions: [215761.04517238 322494.20459726 213289.45871618  59402.41539407
 197863.74576945]


In [7]:
print("Labels:",list(some_labels))

Labels: [286600.0, 340600.0, 196900.0, 46300.0, 254500.0]


In [8]:
from sklearn.metrics import mean_squared_error
housing_predictions=lin_reg.predict(housing_train)
lin_mse=mean_squared_error(housing_labels,housing_predictions)
lim_rmse=np.sqrt(lin_mse)

In [9]:
from sklearn.tree import DecisionTreeRegressor
tree_reg=DecisionTreeRegressor()
tree_reg.fit(housing_train,housing_labels)
housing_predictions_tree=tree_reg.predict(housing_train)
tree_rmse=mean_squared_error(housing_labels,housing_predictions_tree)
tree_rmse

0.0

In [10]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(tree_reg,housing_train,housing_labels,scoring="neg_mean_squared_error",cv=10)
tree_rmse_scores=np.sqrt(-scores)


In [11]:
def display_scores(scores):
    print("Scores:",scores)
    print("Mean:",scores.mean())
    print("Standard deviation:",scores.std())
    

In [12]:
display_scores(tree_rmse_scores)

Scores: [67734.53406322 70976.95972919 68219.25434241 70616.3276953
 68813.02993146 73122.7095406  66753.93117256 63902.60498762
 74198.58285411 67762.35552436]
Mean: 69210.0289840815
Standard deviation: 2913.89278214742


In [13]:
from sklearn.ensemble import RandomForestRegressor
forest_reg=RandomForestRegressor()
forest_reg.fit(housing_train,housing_labels)
forest_scores=cross_val_score(forest_reg,housing_train,housing_labels,scoring="neg_mean_squared_error",cv=10)
forest_rmse_scores=np.sqrt(-forest_scores)

In [14]:
display_scores(forest_rmse_scores)

Scores: [48492.32633039 46479.28728766 49052.38332762 51438.49394679
 48272.57842607 53332.26118405 47713.59028646 47443.62360254
 51685.73567032 49584.81320812]
Mean: 49349.50932699982
Standard deviation: 2055.945605111796


In [15]:
#import Search

In [ ]:
#final_model=Search.grid_search.best_estimator_