In [1]:
import import_ipynb
import pandas as pd
import model
import numpy as np

importing Jupyter notebook from model.ipynb
importing Jupyter notebook from Pipeline.ipynb
importing Jupyter notebook from DownloadingData.ipynb
importing Jupyter notebook from Testsetsplit.ipynb
StratifiedShuffleSplit(n_splits=1, random_state=42, test_size=0.2,
            train_size=None)
importing Jupyter notebook from MyTransformer.ipynb
importing Jupyter notebook from Data_Preparation.ipynb
[-118.51     34.26     29.     2119.5     433.     1164.      408.
    3.5409]
longitude             -118.5100
latitude                34.2600
housing_median_age      29.0000
total_rooms           2119.5000
total_bedrooms         433.0000
population            1164.0000
households             408.0000
median_income            3.5409
dtype: float64
[[-121.89     37.29     38.     ...  710.      339.        2.7042]
 [-121.93     37.05     14.     ...  306.      113.        6.4214]
 [-117.2      32.77     31.     ...  936.      462.        2.8621]
 ...
 [-116.4      34.09      9.     ... 2098.    

In [2]:
housing_train=model.housing_train
housing_labels=model.housing_labels
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid=[{'n_estimators':[3,10,30],'max_features':[2,4,6,8]}]
forest_reg=RandomForestRegressor()
grid_search=GridSearchCV(forest_reg,param_grid,cv=5,scoring="neg_mean_squared_error",return_train_score=True)
grid_search.fit(housing_train,housing_labels)

GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0,
                                             criterion='mse', max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             max_samples=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100, n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='deprecated', n_jo

In [3]:
grid_search.best_params_

{'max_features': 8, 'n_estimators': 30}

In [4]:
grid_search.best_estimator_

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features=8, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=30, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [5]:
cvres=grid_search.cv_results_
for mean_score,params in zip(cvres["mean_test_score"],cvres["params"]):
    print(np.sqrt(-mean_score),params)

63581.53028097537 {'max_features': 2, 'n_estimators': 3}
54745.257476187224 {'max_features': 2, 'n_estimators': 10}
52824.51775648223 {'max_features': 2, 'n_estimators': 30}
59336.4562118015 {'max_features': 4, 'n_estimators': 3}
52236.86477248254 {'max_features': 4, 'n_estimators': 10}
49881.7803406037 {'max_features': 4, 'n_estimators': 30}
57691.855865304446 {'max_features': 6, 'n_estimators': 3}
50958.52842549556 {'max_features': 6, 'n_estimators': 10}
49420.69435611154 {'max_features': 6, 'n_estimators': 30}
58129.13413330922 {'max_features': 8, 'n_estimators': 3}
51353.900838679874 {'max_features': 8, 'n_estimators': 10}
49361.31351357954 {'max_features': 8, 'n_estimators': 30}


In [6]:
cvres

{'mean_fit_time': array([0.09400539, 0.30621758, 0.90545173, 0.13680787, 0.44962568,
        1.35587754, 0.18761072, 0.64583688, 1.80690336, 0.22681293,
        0.76604385, 2.2679297 ]),
 'std_fit_time': array([0.0032866 , 0.00541878, 0.01273792, 0.00391938, 0.00480025,
        0.03570849, 0.00372036, 0.02166601, 0.01417693, 0.00213567,
        0.02066026, 0.00856556]),
 'mean_score_time': array([0.00420022, 0.01160059, 0.03140187, 0.00400028, 0.0108006 ,
        0.03060169, 0.00440021, 0.0120007 , 0.03100171, 0.00420027,
        0.01240072, 0.0304018 ]),
 'std_score_time': array([3.99947177e-04, 8.00001633e-04, 2.80022622e-03, 1.16800773e-07,
        4.00066376e-04, 4.89940339e-04, 8.00037398e-04, 6.32485093e-04,
        6.32485093e-04, 3.99923339e-04, 1.35652236e-03, 4.89901406e-04]),
 'param_max_features': masked_array(data=[2, 2, 2, 4, 4, 4, 6, 6, 6, 8, 8, 8],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False]

In [7]:
feature_importances=grid_search.best_estimator_.feature_importances_
feature_importances

array([7.71703499e-02, 7.16471330e-02, 4.13465060e-02, 1.64681924e-02,
       1.62033182e-02, 1.50810177e-02, 1.52821335e-02, 3.67697495e-01,
       1.18273127e-01, 8.04179210e-02, 1.31182282e-02, 1.62178617e-01,
       1.02693420e-04, 2.86852828e-03, 2.14473922e-03])

In [8]:
import Pipeline

In [9]:
extra_attribs=["rooms_per_hhold","pop_per_hhold","bedrooms_per_room"]
cat_encoder=Pipeline.full_pipeline.named_transformers_["cat"]
cat_one_hot_attribs=list(cat_encoder.categories_[0])
attributes=Pipeline.num_attr + extra_attribs + cat_one_hot_attribs

In [10]:
sorted(zip(feature_importances,attributes),reverse=True)#shows the importance of each feature.Useful for dropping columns which are not reliable.

[(0.36769749545537445, 'median_income'),
 (0.16217861674463208, '<1H OCEAN'),
 (0.11827312686334232, 'rooms_per_hhold'),
 (0.08041792101622257, 'pop_per_hhold'),
 (0.07717034994794017, 'longitude'),
 (0.07164713297740541, 'latitude'),
 (0.04134650601225136, 'housing_median_age'),
 (0.016468192355416005, 'total_rooms'),
 (0.016203318233564815, 'total_bedrooms'),
 (0.01528213354285991, 'households'),
 (0.015081017733160746, 'population'),
 (0.013118228190941814, 'bedrooms_per_room'),
 (0.0028685282843713598, 'ISLAND'),
 (0.002144739222288096, 'NEAR BAY'),
 (0.00010269342022897838, 'INLAND')]

In [11]:
import Testsetsplit

final_model=grid_search.best_estimator_
X_test=Testsetsplit.strat_test_set.drop(columns="median_house_value")
y_test=Testsetsplit.strat_test_set["median_house_value"].copy()

In [12]:
X_test_prepared=Pipeline.full_pipeline.transform(X_test)

In [14]:
from sklearn.metrics import mean_squared_error
final_predictions=final_model.predict(X_test_prepared)
final_mse=mean_squared_error(y_test,final_predictions)
final_rmse=np.sqrt(final_mse)

In [15]:
final_rmse

47677.53373066988

In [2]:
print(cat_encoder.categories_)

NameError: name 'cat_encoder' is not defined