In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
train=pd.read_csv("train.csv")

In [3]:
train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
train.shape

(891, 12)

In [69]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          891 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB


In [42]:
train["SibSp"].value_counts()
train["Parch"].value_counts()

0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: Parch, dtype: int64

In [3]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='median')
imputer.fit(np.array(train['Age']).reshape(-1,1))
imputedage=imputer.transform(np.array(train['Age']).reshape(-1,1))

In [4]:
train['Age']=imputedage
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [5]:
train["Survived"].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [6]:
corr_matrix=train.corr()
corr_matrix['Survived']

PassengerId   -0.005007
Survived       1.000000
Pclass        -0.338481
Age           -0.064910
SibSp         -0.035322
Parch          0.081629
Fare           0.257307
Name: Survived, dtype: float64

In [7]:
train['Cabin'].value_counts()

B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F2             3
              ..
A16            1
E17            1
C101           1
C99            1
F E69          1
Name: Cabin, Length: 147, dtype: int64

In [8]:
traincabin=train.copy(deep=True)

In [9]:
traincabin['Cabin'].value_counts()

B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F2             3
              ..
A16            1
E17            1
C101           1
C99            1
F E69          1
Name: Cabin, Length: 147, dtype: int64

In [10]:
traincabin["Cabin"].fillna(0,inplace=True)
filt=traincabin['Cabin']==0
traincabin.loc[~filt,'Cabin']=1
traincabin['Cabin']=traincabin['Cabin'].astype(int)
traincabin["Cabin"].value_counts()

0    687
1    204
Name: Cabin, dtype: int64

In [11]:
corr_mat=traincabin.corr()
corr_mat["Survived"]

PassengerId   -0.005007
Survived       1.000000
Pclass        -0.338481
Age           -0.064910
SibSp         -0.035322
Parch          0.081629
Fare           0.257307
Cabin          0.316912
Name: Survived, dtype: float64

In [12]:
filt=(traincabin["Cabin"]==1) & (traincabin["Survived"]==1)
traincabin.loc[filt].count()

PassengerId    136
Survived       136
Pclass         136
Name           136
Sex            136
Age            136
SibSp          136
Parch          136
Ticket         136
Fare           136
Cabin          136
Embarked       134
dtype: int64

In [13]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder=OrdinalEncoder()
sexencoded=ordinal_encoder.fit_transform(traincabin[["Sex"]])
traincabin["Sex"]=sexencoded

In [14]:
traincabin["Sex"].value_counts()

1.0    577
0.0    314
Name: Sex, dtype: int64

In [27]:
sexencoded

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [15]:
traincabin[(traincabin["Sex"]=="female")&(traincabin["Survived"]==1)].count()

D:\anaconda\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)


PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [16]:
traincabin["Embarked"].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [17]:
traincabin[(traincabin["Embarked"]=='Q') & (traincabin["Survived"]==1)].count()

PassengerId    30
Survived       30
Pclass         30
Name           30
Sex            30
Age            30
SibSp          30
Parch          30
Ticket         30
Fare           30
Cabin          30
Embarked       30
dtype: int64

In [29]:
wanted_features=["Pclass","Sex","Age","SibSp","Parch","Fare","Cabin"]


In [53]:
traincabin

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris  1.0  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  0.0  38.0      1   
2                               Heikkinen, Miss. Laina  0.0  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  0.0  35.0      1   
4                             Allen, Mr. William Henry  1.0  35.0      0   
..                                                 ...  ...   ...    ...   
886                              Montvila, Rev. Juozas  1.0  27.0      0   
887                       Graham, Miss. Margaret Edith  0.0  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  0.0  28.0      1   
889                              Behr, Mr. Karl Howell  1.0  26.0      0   
890                                Dooley, Mr. Patrick  1.0  32.0      0   

     Parch            Ticket     Fare  Cabin Embarked  
0        0         A/5 21171   7.2500      0        S  
1        0          PC 17599  71.2833      1        C  
2        0  STON/O2. 3101282   7.9250      0        S  
3        0            113803  53.1000      1        S  
4        0            373450   8.0500      0        S  
..     ...               ...      ...    ...      ...  
886      0            211536  13.0000      0        S  
887      0            112053  30.0000      1        S  
888      2        W./C. 6607  23.4500      0        S  
889      0            111369  30.0000      1        C  
890      0            370376   7.7500      0        Q  

[891 rows x 12 columns]

In [63]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaledtraincabin=scaler.fit_transform(traincabin[wanted_features])
scaledtraincabin


array([[ 0.82737724,  0.73769513, -0.56573646, ..., -0.47367361,
        -0.50244517, -0.54492498],
       [-1.56610693, -1.35557354,  0.66386103, ..., -0.47367361,
         0.78684529,  1.835115  ],
       [ 0.82737724, -1.35557354, -0.25833709, ..., -0.47367361,
        -0.48885426, -0.54492498],
       ...,
       [ 0.82737724, -1.35557354, -0.1046374 , ...,  2.00893337,
        -0.17626324, -0.54492498],
       [-1.56610693,  0.73769513, -0.25833709, ..., -0.47367361,
        -0.04438104,  1.835115  ],
       [ 0.82737724,  0.73769513,  0.20276197, ..., -0.47367361,
        -0.49237783, -0.54492498]])

In [22]:
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import cross_val_score


In [67]:
from sklearn.ensemble import RandomForestClassifier
forestclassifier=RandomForestClassifier()
forestpred=cross_val_predict(forestclassifier,train_fareperperson,traincabin["Survived"],cv=3)

In [68]:
from sklearn.linear_model import SGDClassifier 
sgdclassifier=SGDClassifier()
sgdpred=cross_val_predict(sgdclassifier,train_fareperperson,traincabin["Survived"],cv=3)

In [69]:
from sklearn.linear_model import LogisticRegression
logclassifier=LogisticRegression()
logclassifierpred=cross_val_predict(logclassifier,train_fareperperson,traincabin["Survived"],cv=3)

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(traincabin["Survived"],forestpred)

array([[478,  71],
       [ 88, 254]], dtype=int64)

In [28]:
#wanted_features=["Pclass","Sex","Age","SibSp","Parch","Fare","Cabin"]
from sklearn.metrics import precision_score,recall_score
print("Randomforest(precision):",precision_score(traincabin["Survived"],forestpred))
print("SGDclassifier(precision):",precision_score(traincabin["Survived"],sgdpred))
print("LogisticRegression(precision):",precision_score(traincabin["Survived"],logclassifierpred))
print("Randomforest(recall):",recall_score(traincabin["Survived"],forestpred))
print("SGDclassifier(recall):",precision_score(traincabin["Survived"],sgdpred))
print("LogisticRegression(recall):",recall_score(traincabin["Survived"],logclassifierpred))


Randomforest(precision): 0.7815384615384615
SGDclassifier(precision): 0.7098976109215017
LogisticRegression(precision): 0.7469135802469136
Randomforest(recall): 0.7426900584795322
SGDclassifier(recall): 0.7098976109215017
LogisticRegression(recall): 0.7076023391812866


In [35]:
#wanted_features=["Pclass","Sex","Age","SibSp","Parch","Fare",]
print("Randomforest(precision):",precision_score(traincabin["Survived"],forestpred))
print("SGDclassifier(precision):",precision_score(traincabin["Survived"],sgdpred))
print("LogisticRegression(precision):",precision_score(traincabin["Survived"],logclassifierpred))
print("Randomforest(recall):",recall_score(traincabin["Survived"],forestpred))
print("SGDclassifier(recall):",precision_score(traincabin["Survived"],sgdpred))
print("LogisticRegression(recall):",recall_score(traincabin["Survived"],logclassifierpred))


Randomforest(precision): 0.7732919254658385
SGDclassifier(precision): 0.6822157434402333
LogisticRegression(precision): 0.7429467084639498
Randomforest(recall): 0.7280701754385965
SGDclassifier(recall): 0.6822157434402333
LogisticRegression(recall): 0.6929824561403509


In [70]:
#wanted_features=["Pclass","Sex","Age","SibSp","Parch","Fare","cabin",Fareperperson"]
print("Randomforest(precision):",precision_score(traincabin["Survived"],forestpred))
print("SGDclassifier(precision):",precision_score(traincabin["Survived"],sgdpred))
print("LogisticRegression(precision):",precision_score(traincabin["Survived"],logclassifierpred))
print("Randomforest(recall):",recall_score(traincabin["Survived"],forestpred))
print("SGDclassifier(recall):",precision_score(traincabin["Survived"],sgdpred))
print("LogisticRegression(recall):",recall_score(traincabin["Survived"],logclassifierpred))


Randomforest(precision): 0.7514792899408284
SGDclassifier(precision): 0.717391304347826
LogisticRegression(precision): 0.7401812688821753
Randomforest(recall): 0.7426900584795322
SGDclassifier(recall): 0.717391304347826
LogisticRegression(recall): 0.716374269005848


In [64]:
from sklearn.base import BaseEstimator,TransformerMixin
spsibling=6
parentchild=7
fare=9
class Attributesadder(BaseEstimator,TransformerMixin):
    def __init__(self,addattributes=True):
        self.addattributes=addattributes
    def fit(self,X,y=None):
        return self
    def transform(self,X,y=None):
        fareperperson=X[:,5]/(1+X[:,3]+X[:,4])
        return np.c_[X,fareperperson]
        
        
        

In [65]:
attradder=Attributesadder()
train_fareperperson=attradder.transform(scaledtraincabin)

In [71]:
train_fareperperson

array([[ 0.82737724,  0.73769513, -0.56573646, ..., -0.50244517,
        -0.54492498, -0.52386073],
       [-1.56610693, -1.35557354,  0.66386103, ...,  0.78684529,
         1.835115  ,  0.82038274],
       [ 0.82737724, -1.35557354, -0.25833709, ..., -0.48885426,
        -0.54492498, -9.44076827],
       ...,
       [ 0.82737724, -1.35557354, -0.1046374 , ..., -0.17626324,
        -0.54492498, -0.05121361],
       [-1.56610693,  0.73769513, -0.25833709, ..., -0.04438104,
         1.835115  , -0.85708795],
       [ 0.82737724,  0.73769513,  0.20276197, ..., -0.49237783,
        -0.54492498, -9.50881557]])

In [59]:
traincabin[wanted_features]

Pclass  Sex   Age  SibSp  Parch     Fare  Cabin
0         3  1.0  22.0      1      0   7.2500      0
1         1  0.0  38.0      1      0  71.2833      1
2         3  0.0  26.0      0      0   7.9250      0
3         1  0.0  35.0      1      0  53.1000      1
4         3  1.0  35.0      0      0   8.0500      0
..      ...  ...   ...    ...    ...      ...    ...
886       2  1.0  27.0      0      0  13.0000      0
887       1  0.0  19.0      0      0  30.0000      1
888       3  0.0  28.0      1      2  23.4500      0
889       1  1.0  26.0      0      0  30.0000      1
890       3  1.0  32.0      0      0   7.7500      0

[891 rows x 7 columns]